name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint (ruff, black, flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Python version
        id: pyver
        run: echo "PYVER=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.pyver.outputs.PYVER }}
          cache: pip

      - name: Install deps + linters
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff black flake8

      - run: ruff check .
      - run: black --check .
      - run: flake8 .

  security:
    name: Security (bandit, pip-audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Python version
        id: pyver
        run: echo "PYVER=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.pyver.outputs.PYVER }}
          cache: pip

      - name: Install deps + security tools
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install bandit pip-audit

      - run: bandit -r . -x tests
      - run: pip-audit -r requirements.txt

  tests:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Python version
        id: pyver
        run: echo "PYVER=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.pyver.outputs.PYVER }}
          cache: pip

      - name: Install deps + pytest
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest

      - run: pytest -q

